baseURL = 'https://francis329.github.io/'
languageCode = 'zh-cn'
title = 'Jun_blog'
publishDir = "docs"

[params]
  [params.assets]
    enableInlineSRI = false
    enableFingerprint = false
    enableCDN = false
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true